
INSERT INTO dbo.tag (name) values
('aquatic'),('autumn'),('bamboo'),('basket'),('black'),('blue'),('blueberry'),
('brown'),('cabinet'),('candy'),('cap'),('castle'),('casual'),('chair'),
('cherry'),('cinnamon'),('classic'),('clouds'),('colorful'),('corduroy'),('couch'),
('counter'),('curtains'),('dog'),('drape'),('drawers'),('embroidered'),('feather'),
('floral'),('flowers'),('fluffy'),('flying'),('fridge'),('furniture'),('galaxies'),
('gingham'),('gradient'),('green'),('ice'),('khaki'),('knitted'),('leaf'),
('leaves'),('lounger'),('magical'),('maroon'),('marshmallow'),('multi'),('music'),
('nature'),('nebula'),('necklaces'),('ocean'),('orange'),('pale'),('palm'),('pantry'),
('pastel'),('patchwork'),('pineapple'),('pink'),('pockets'),('popcorn'),('puffy'),
('purple'),('rain'),('rainbow'),('raspberry'),('red'),('refrigerator'),('retro'),
('rustic'),('sand'),('sea'),('seashell'),('seating'),('shirt'),('sky'),('space'),
('sparkly'),('spikes'),('stars'),('strawberry'),('stripes'),('sunny'),('table'),
('tan'),('tropical'),('umbrella'),('vintage'),('water'),('watermelon'),('waves'),
('white'),('winter'),('yarn'),('yellow');
GO

INSERT INTO dbo.productTag (productId, tagId)
  SELECT p.productId, t.tagId
  FROM (VALUES
    ('acorn-cap-slippers', 'autumn'),
    ('acorn-cap-slippers', 'brown'),
    ('apple-cider-mittens', 'autumn'),
    ('apple-cider-mittens', 'knitted'),
    ('apple-cider-mittens', 'red'),
    ('apple-cider-mittens', 'yarn'),
    ('autumn-plaid-skirt', 'leaf'),
    ('autumn-plaid-skirt', 'leaves'),
    ('autumn-plaid-skirt', 'orange'),
    ('autumn-vineyard-wallpaper', 'autumn'),
    ('autumn-vineyard-wallpaper', 'blue'),
    ('autumn-vineyard-wallpaper', 'rustic'),
    ('autumn-vineyard-wallpaper', 'sky'),
    ('barn-board-wallpaper', 'maroon'),
    ('barn-board-wallpaper', 'red'),
    ('barn-board-wallpaper', 'rustic'),
    ('barn-board-wallpaper', 'vintage'),
    ('berry-patch-carpet', 'blueberry'),
    ('berry-patch-carpet', 'nature'),
    ('berry-patch-carpet', 'purple'),
    ('berry-patch-carpet', 'raspberry'),
    ('berry-patch-carpet', 'red'),
    ('berry-patch-carpet', 'strawberry'),
    ('blueberry-pie-bed', 'marshmallow'),
    ('blueberry-pie-bed', 'purple'),
    ('blueberry-pie-bed', 'tan'),
    ('bunk-bed-fort', 'colorful'),
    ('bunk-bed-fort', 'furniture'),
    ('bunk-bed-fort', 'multi'),
    ('cargo-shorts', 'khaki'),
    ('cargo-shorts', 'pockets'),
    ('cargo-shorts', 'tan'),
    ('cast-iron-stove', 'black'),
    ('cast-iron-stove', 'furniture'),
    ('cast-iron-stove', 'rustic'),
    ('cast-iron-stove', 'vintage'),
    ('checkerboard-kitchen-tiles', 'black'),
    ('checkerboard-kitchen-tiles', 'classic'),
    ('checkerboard-kitchen-tiles', 'retro'),
    ('checkerboard-kitchen-tiles', 'white'),
    ('cherry-blossom-panda', 'black'),
    ('cherry-blossom-panda', 'pink'),
    ('cherry-blossom-panda', 'white'),
    ('cider-mill-pants', 'autumn'),
    ('cider-mill-pants', 'brown'),
    ('cider-mill-pants', 'cinnamon'),
    ('cider-mill-pants', 'corduroy'),
    ('cider-mill-pants', 'gingham'),
    ('cider-mill-pants', 'maroon'),
    ('cloud-sheep', 'fluffy'),
    ('cloud-sheep', 'white'),
    ('cloud-sneakers', 'fluffy'),
    ('cloud-sneakers', 'puffy'),
    ('cloud-sneakers', 'white'),
    ('cocoa-corgi', 'brown'),
    ('cocoa-corgi', 'cinnamon'),
    ('cocoa-corgi', 'dog'),
    ('cocoa-corgi', 'tan'),
    ('coconut-cooler-fridge', 'brown'),
    ('coconut-cooler-fridge', 'leaf'),
    ('coconut-cooler-fridge', 'leaves'),
    ('coconut-cooler-fridge', 'furniture'),
    ('coconut-cooler-fridge', 'palm'),
    ('coconut-cooler-fridge', 'fridge'),
    ('coconut-cooler-fridge', 'refrigerator'),
    ('coconut-cooler-fridge', 'tropical'),
    ('corn-maze-flooring', 'autumn'),
    ('corn-maze-flooring', 'nature'),
    ('corn-maze-flooring', 'rustic'),
    ('corn-maze-flooring', 'yellow'),
    ('crystal-fox', 'blue'),
    ('crystal-fox', 'pale'),
    ('crystal-fox', 'pastel'),
    ('crystal-fox', 'sparkly'),
    ('crystal-fox', 'white'),
    ('crystal-fox', 'winter'),
    ('driftwood-canopy-bed', 'curtains'),
    ('driftwood-canopy-bed', 'drape'),
    ('driftwood-canopy-bed', 'furniture'),
    ('driftwood-canopy-bed', 'ocean'),
    ('driftwood-canopy-bed', 'rustic'),
    ('driftwood-canopy-bed', 'sea'),
    ('driftwood-canopy-bed', 'seashell'),
    ('driftwood-canopy-bed', 'tan'),
    ('driftwood-canopy-bed', 'waves'),
    ('driftwood-lounger', 'brown'),
    ('driftwood-lounger', 'chair'),
    ('driftwood-lounger', 'furniture'),
    ('driftwood-lounger', 'ocean'),
    ('driftwood-lounger', 'rustic'),
    ('driftwood-lounger', 'sea'),
    ('driftwood-lounger', 'seating'),
    ('driftwood-lounger', 'water'),
    ('driftwood-lounger', 'waves'),
    ('fallen-leaves-carpet', 'autumn'),
    ('fallen-leaves-carpet', 'brown'),
    ('fallen-leaves-carpet', 'nature'),
    ('fallen-leaves-carpet', 'orange'),
    ('fallen-leaves-carpet', 'red')
  ) AS mapping(productSlug, tagName)
  JOIN dbo.product p ON p.slug = mapping.productSlug
  JOIN dbo.tag t ON t.name = mapping.tagName;
GO

INSERT INTO dbo.productTag (productId, tagId)
  SELECT p.productId, t.tagId
  FROM (VALUES
    ('fruit-salad-wallpaper', 'cherry'),
    ('fruit-salad-wallpaper', 'colorful'),
    ('fruit-salad-wallpaper', 'floral'),
    ('fruit-salad-wallpaper', 'flowers'),
    ('fruit-salad-wallpaper', 'pineapple'),
    ('fruit-salad-wallpaper', 'tropical'),
    ('fruit-salad-wallpaper', 'watermelon'),
    ('galaxy-tank', 'black'),
    ('galaxy-tank', 'blue'),
    ('galaxy-tank', 'galaxies'),
    ('galaxy-tank', 'nebula'),
    ('galaxy-tank', 'purple'),
    ('galaxy-tank', 'space'),
    ('galaxy-tank', 'stars'),
    ('giant-orange-slice-chair', 'furniture'),
    ('giant-orange-slice-chair', 'seating'),
    ('giant-orange-slice-chair', 'tropical'),
    ('glow-galaxy-wallpaper', 'black'),
    ('glow-galaxy-wallpaper', 'blue'),
    ('glow-galaxy-wallpaper', 'galaxies'),
    ('glow-galaxy-wallpaper', 'nebula'),
    ('glow-galaxy-wallpaper', 'purple'),
    ('glow-galaxy-wallpaper', 'space'),
    ('glow-galaxy-wallpaper', 'stars'),
    ('harvest-festival-scarf', 'autumn'),
    ('harvest-festival-scarf', 'gradient'),
    ('harvest-festival-scarf', 'green'),
    ('harvest-festival-scarf', 'knitted'),
    ('harvest-festival-scarf', 'orange'),
    ('harvest-festival-scarf', 'red'),
    ('harvest-festival-scarf', 'yarn'),
    ('harvest-festival-scarf', 'yellow'),
    ('harvest-hutch', 'autumn'),
    ('harvest-hutch', 'brown'),
    ('harvest-hutch', 'cabinet'),
    ('harvest-hutch', 'drawers'),
    ('harvest-hutch', 'furniture'),
    ('harvest-hutch', 'pantry'),
    ('harvest-hutch', 'rustic'),
    ('harvest-hutch', 'vintage'),
    ('harvest-moon-bed', 'autumn'),
    ('harvest-moon-bed', 'brown'),
    ('harvest-moon-bed', 'furniture'),
    ('harvest-moon-bed', 'orange'),
    ('harvest-moon-hoodie', 'autumn'),
    ('harvest-moon-hoodie', 'basket'),
    ('harvest-moon-hoodie', 'leaf'),
    ('harvest-moon-hoodie', 'leaves'),
    ('harvest-moon-hoodie', 'orange'),
    ('hay-bale-bench', 'chair'),
    ('hay-bale-bench', 'furniture'),
    ('hay-bale-bench', 'red'),
    ('hay-bale-bench', 'rustic'),
    ('hay-bale-bench', 'seating'),
    ('hay-bale-bench', 'tan'),
    ('hot-chocolate-bar', 'brown'),
    ('hot-chocolate-bar', 'counter'),
    ('hot-chocolate-bar', 'furniture'),
    ('hot-chocolate-bar', 'table'),
    ('leaf-pile-boots', 'autumn'),
    ('leaf-pile-boots', 'colorful'),
    ('leaf-pile-boots', 'green'),
    ('leaf-pile-boots', 'leaves'),
    ('leaf-pile-boots', 'rain'),
    ('maple-leaf-sweater', 'autumn'),
    ('maple-leaf-sweater', 'leaves'),
    ('maple-leaf-sweater', 'orange'),
    ('maple-leaf-sweater', 'red'),
    ('maple-leaf-sweater', 'tan'),
    ('mason-jar-cabinet', 'brown'),
    ('mason-jar-cabinet', 'furniture'),
    ('mason-jar-cabinet', 'rustic'),
    ('mason-jar-cabinet', 'vintage'),
    ('midnight-snack-station', 'candy'),
    ('midnight-snack-station', 'furniture'),
    ('midnight-snack-station', 'popcorn'),
    ('midnight-snack-station', 'red'),
    ('mini-mint-turtle', 'aquatic'),
    ('mini-mint-turtle', 'green'),
    ('ocean-wave-top', 'blue'),
    ('ocean-wave-top', 'ocean'),
    ('ocean-wave-top', 'sea'),
    ('ocean-wave-top', 'water'),
    ('ocean-wave-top', 'waves'),
    ('orange-corgi', 'brown'),
    ('orange-corgi', 'dog'),
    ('orange-corgi', 'tan'),
    ('patchwork-flooring', 'colorful'),
    ('patchwork-flooring', 'green'),
    ('patchwork-flooring', 'multi'),
    ('patchwork-flooring', 'pastel'),
    ('patchwork-flooring', 'red'),
    ('patchwork-flooring', 'yellow'),
    ('pineapple-prep-station', 'cabinet'),
    ('pineapple-prep-station', 'colorful'),
    ('pineapple-prep-station', 'drawers'),
    ('pineapple-prep-station', 'furniture'),
    ('pineapple-prep-station', 'multi'),
    ('pineapple-prep-station', 'tropical'),
    ('pineapple-prep-station', 'yellow')
  ) AS mapping(productSlug, tagName)
  JOIN dbo.product p ON p.slug = mapping.productSlug
  JOIN dbo.tag t ON t.name = mapping.tagName;
GO

INSERT INTO dbo.productTag (productId, tagId)
  SELECT p.productId, t.tagId
  FROM (VALUES
    ('pink-blouse', 'casual'),
    ('pink-blouse', 'pastel'),
    ('pink-blouse', 'shirt'),
    ('pocket-hedgehog', 'brown'),
    ('pocket-hedgehog', 'tan'),
    ('pumpkin-carriage-seat', 'autumn'),
    ('pumpkin-carriage-seat', 'chair'),
    ('pumpkin-carriage-seat', 'furniture'),
    ('pumpkin-carriage-seat', 'lounger'),
    ('pumpkin-carriage-seat', 'orange'),
    ('pumpkin-patch-overalls', 'autumn'),
    ('pumpkin-patch-overalls', 'blue'),
    ('pumpkin-patch-overalls', 'embroidered'),
    ('pumpkin-patch-overalls', 'orange'),
    ('quilted-barn-bed', 'brown'),
    ('quilted-barn-bed', 'furniture'),
    ('quilted-barn-bed', 'patchwork'),
    ('quilted-barn-bed', 'red'),
    ('quilted-barn-bed', 'rustic'),
    ('rainbow-octopus', 'multi'),
    ('rainbow-octopus', 'ocean'),
    ('rainbow-octopus', 'pastel'),
    ('rainbow-octopus', 'sea'),
    ('rainbow-octopus', 'yellow'),
    ('rainbow-tutu', 'colorful'),
    ('rainbow-tutu', 'multi'),
    ('red-rocker-collar', 'music'),
    ('red-rocker-collar', 'necklaces'),
    ('red-rocker-collar', 'red'),
    ('red-rocker-collar', 'spikes'),
    ('red-velvet-cat', 'pink'),
    ('sandy-shore-rug', 'castle'),
    ('sandy-shore-rug', 'nature'),
    ('sandy-shore-rug', 'ocean'),
    ('sandy-shore-rug', 'sand'),
    ('sandy-shore-rug', 'tan'),
    ('sleeping-bag-sofa', 'colorful'),
    ('sleeping-bag-sofa', 'couch'),
    ('sleeping-bag-sofa', 'furniture'),
    ('sleeping-bag-sofa', 'multi'),
    ('sleeping-bag-sofa', 'rainbow'),
    ('snowflake-penguin', 'blue'),
    ('snowflake-penguin', 'ice'),
    ('snowflake-penguin', 'pastel'),
    ('snowflake-penguin', 'white'),
    ('snowflake-penguin', 'winter'),
    ('star-sweater', 'colorful'),
    ('star-sweater', 'multi'),
    ('star-sweater', 'rainbow'),
    ('star-sweater', 'shirt'),
    ('star-sweater', 'tan'),
    ('stardust-dragon', 'flying'),
    ('stardust-dragon', 'magical'),
    ('stardust-dragon', 'pastel'),
    ('stardust-dragon', 'purple'),
    ('stardust-dragon', 'space'),
    ('starlight-dress', 'purple'),
    ('starlight-dress', 'space'),
    ('sunflower-sundress', 'floral'),
    ('sunflower-sundress', 'sunny'),
    ('sunflower-sundress', 'yellow'),
    ('sunset-tiger', 'orange'),
    ('sunset-tiger', 'stripes'),
    ('tiki-bar-counter', 'bamboo'),
    ('tiki-bar-counter', 'brown'),
    ('tiki-bar-counter', 'furniture'),
    ('tiki-bar-counter', 'table'),
    ('tiki-bar-counter', 'tan'),
    ('tiki-bar-counter', 'tropical'),
    ('tiki-bar-counter', 'umbrella'),
    ('tropical-horizon-wallpaper', 'blue'),
    ('tropical-horizon-wallpaper', 'clouds'),
    ('tropical-horizon-wallpaper', 'ocean'),
    ('tropical-horizon-wallpaper', 'sea'),
    ('tropical-horizon-wallpaper', 'tropical'),
    ('tropical-horizon-wallpaper', 'water'),
    ('turkey-trot-hat', 'autumn'),
    ('turkey-trot-hat', 'black'),
    ('turkey-trot-hat', 'cap'),
    ('turkey-trot-hat', 'feather'),
    ('watermelon-refrigerator', 'fridge'),
    ('watermelon-refrigerator', 'refrigerator'),
    ('watermelon-refrigerator', 'green'),
    ('watermelon-refrigerator', 'furniture'),
    ('watermelon-refrigerator', 'red'),
    ('watermelon-refrigerator', 'tropical')
  ) AS mapping(productSlug, tagName)
  JOIN dbo.product p ON p.slug = mapping.productSlug
  JOIN dbo.tag t ON t.name = mapping.tagName;
GO
